# SPDX-FileCopyrightText: 2025 The Karei Authors
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "**.md"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.adoc"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.sh"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "justfile"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.fish"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.yaml"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.yml"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.toml"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.json"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.conf"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.desktop"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.theme"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.kdl"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.lua"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.css"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "dircolors"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/dircolors"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "version"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "versions.conf"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "xcompose"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/xcompose"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitkeep"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/.gitkeep"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

# Binary and generated files that should be ignored
[[annotations]]
path = "**.gz"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.png"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.jpg"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.msgpack.z"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

# Exclude cache files
[[annotations]]
path = "${XDG_CACHE_HOME:-$HOME/.cache}/**"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

# Test fixture files
[[annotations]]
path = "test/fixtures/**"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

# Generated files
[[annotations]]
path = "generated/**"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

# Binary executables
[[annotations]]
path = "karei"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "main"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "test_build"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

# Test scripts without extension
[[annotations]]
path = "test_*.sh"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "test_aqua_integration.sh"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "test_aqua_paths.sh"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "test_all_just_targets.sh"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "test_machine_readable_output.sh"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "fix-mise-tools.sh"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

# Additional files
[[annotations]]
path = ".shellcheckrc"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "bin/**"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.jsonc"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "configs/fish.config"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "configs/ghostty/config"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "defaults/fish/conf.d/15-vi-mode.fish.disabled"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "go.mod"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "go.sum"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "tools/go.mod"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "tools/go.sum"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.backup"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.go"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "EUPL-1.2"

# Test files and build artifacts
[[annotations]]
path = "test/unit.test"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = "test-build"
SPDX-FileCopyrightText = "2025 The Karei Authors"
SPDX-License-Identifier = "EUPL-1.2"