format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$kubernetes\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[>](purple)"
error_symbol = "[>](red)"
vimcmd_symbol = "[<](green)"
vimcmd_replace_one_symbol	= "[<](purple)"
vimcmd_replace_symbol =	"[<](purple)"
vimcmd_visual_symbol =	"[<](yellow)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[kubernetes]
disabled=false
format = "[$symbol$context/$namespace]($style)"
detect_extensions = ['yaml', 'yml']

[[kubernetes.contexts]]
# Use capture groups to extract cluster and username to shorten display
context_pattern = ".*/api-(?P<cluster>\\w+).*"
context_alias = "$cluster"
user_pattern = "(?P<username>\\w+)/.*"
user_alias = "$username"
symbol = "⎈ "